/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Room = IDL.Record({
  'id' : IDL.Nat,
  'viewDuration' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'createdAt' : Time,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'creatorName' : IDL.Text,
  'category' : IDL.Text,
  'embedScript' : IDL.Text,
  'price' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const VideoSubmission = IDL.Record({
  'id' : IDL.Nat,
  'viewDuration' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'submitterPrincipal' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'paymentAddress' : IDL.Text,
  'creatorName' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Text,
  'videoUrl' : IDL.Text,
  'denialReason' : IDL.Text,
});

export const HomepageScript = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'scriptContent' : IDL.Text,
  'order' : IDL.Nat,
});
export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimHardcodedAdmin' : IDL.Func([], [IDL.Bool], []),
  'createRoom' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Room],
      [],
    ),
  'deleteRoom' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingSubmissions' : IDL.Func([], [IDL.Vec(VideoSubmission)], ['query']),
  'getRoomById' : IDL.Func([IDL.Nat], [IDL.Opt(Room)], ['query']),
  'getRoomBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Room)], ['query']),
  'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubmissions' : IDL.Func([], [IDL.Vec(VideoSubmission)], ['query']),
  'hasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'addHomepageScript' : IDL.Func([IDL.Text, IDL.Text], [HomepageScript], []),
    'getHomepageScripts' : IDL.Func([], [IDL.Vec(HomepageScript)], ['query']),
    'updateHomepageScript' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [HomepageScript], []),
    'removeHomepageScript' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'reorderHomepageScripts' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'resetAdmin' : IDL.Func([], [], []),
  'reviewSubmission' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Text, IDL.Text],
      [VideoSubmission],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [VideoSubmission],
      [],
    ),
  'updateRoom' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Room],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Room = IDL.Record({
    'id' : IDL.Nat,
    'viewDuration' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'createdAt' : Time,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'creatorName' : IDL.Text,
    'category' : IDL.Text,
    'embedScript' : IDL.Text,
    'price' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const VideoSubmission = IDL.Record({
    'id' : IDL.Nat,
    'viewDuration' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'submitterPrincipal' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'paymentAddress' : IDL.Text,
    'creatorName' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Text,
    'videoUrl' : IDL.Text,
    'denialReason' : IDL.Text,
  });
  
  const HomepageScript = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'scriptContent' : IDL.Text,
    'order' : IDL.Nat,
  });
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimHardcodedAdmin' : IDL.Func([], [IDL.Bool], []),
    'createRoom' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Room],
        [],
      ),
    'deleteRoom' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingSubmissions' : IDL.Func(
        [],
        [IDL.Vec(VideoSubmission)],
        ['query'],
      ),
    'getRoomById' : IDL.Func([IDL.Nat], [IDL.Opt(Room)], ['query']),
    'getRoomBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Room)], ['query']),
    'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubmissions' : IDL.Func([], [IDL.Vec(VideoSubmission)], ['query']),
    'hasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'addHomepageScript' : IDL.Func([IDL.Text, IDL.Text], [HomepageScript], []),
    'getHomepageScripts' : IDL.Func([], [IDL.Vec(HomepageScript)], ['query']),
    'updateHomepageScript' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [HomepageScript], []),
    'removeHomepageScript' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'reorderHomepageScripts' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'resetAdmin' : IDL.Func([], [], []),
    'reviewSubmission' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Text, IDL.Text],
        [VideoSubmission],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [VideoSubmission],
        [],
      ),
    'updateRoom' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Room],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
