/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Room {
  'id' : bigint,
  'viewDuration' : string,
  'title' : string,
  'thumbnailUrl' : string,
  'createdAt' : Time,
  'slug' : string,
  'description' : string,
  'creatorName' : string,
  'category' : string,
  'embedScript' : string,
  'price' : string,
  'videoUrl' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoSubmission {
  'id' : bigint,
  'viewDuration' : string,
  'status' : string,
  'title' : string,
  'thumbnailUrl' : string,
  'submitterPrincipal' : Principal,
  'createdAt' : Time,
  'description' : string,
  'paymentAddress' : string,
  'creatorName' : string,
  'category' : string,
  'price' : string,
  'videoUrl' : string,
  'denialReason' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface HomepageScript {
  'id' : bigint,
  'name' : string,
  'scriptContent' : string,
  'order' : bigint,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bootstrapAdminIfNeeded' : ActorMethod<[], boolean>,
  'claimHardcodedAdmin' : ActorMethod<[], boolean>,
  'createRoom' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    Room
  >,
  'deleteRoom' : ActorMethod<[bigint], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPendingSubmissions' : ActorMethod<[], Array<VideoSubmission>>,
  'getRoomById' : ActorMethod<[bigint], [] | [Room]>,
  'getRoomBySlug' : ActorMethod<[string], [] | [Room]>,
  'getRooms' : ActorMethod<[], Array<Room>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubmissions' : ActorMethod<[], Array<VideoSubmission>>,
  'hasAdmin' : ActorMethod<[], boolean>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'addHomepageScript' : ActorMethod<[string, string], HomepageScript>,
  'getHomepageScripts' : ActorMethod<[], Array<HomepageScript>>,
  'updateHomepageScript' : ActorMethod<[bigint, string, string], HomepageScript>,
  'removeHomepageScript' : ActorMethod<[bigint], boolean>,
  'reorderHomepageScripts' : ActorMethod<[Array<bigint>], undefined>,
  'resetAdmin' : ActorMethod<[], undefined>,
  'reviewSubmission' : ActorMethod<[bigint, boolean, string, string], VideoSubmission>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitVideo' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    VideoSubmission
  >,
  'updateRoom' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    Room
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
